function numberToWords(n){
    if(n==0){
        console.log("zero")
    }
    if(n==1){
        console.log("one")
    }
    if(n==2){
        console.log("two")
    }
    if(n==3){
        console.log("three")
    }
    if(n==4){
        console.log("four")
    }
    if(n==5){
        console.log("five")
    }
    if(n==6){
        console.log("six")
    }
    if(n==7){
        console.log("seven")
    }
    if(n==8){
        console.log("eight")
    }
    if(n==9){
        console.log("nine")
    }
}